name: Crypti.cc
description: Adam Pritchard's blog, resume, projects, etc.
url: https://www.crypti.cc

myfullname: Adam Pritchard

exclude:
- README.md
- node_modules
- less

titleprefix: adam-p

navigation:
- text: Blog
  url: /blog/
  name: blog
- text: In/Co
  url: /inco/
  name: inco
- text: Projects
  url: /projects/
  name: projects
- text: CV
  url: /cv/
  name: cv
- text: Contact
  url: /contact/
  name: contact
