name: Adam Pritchard
description: coder, etc.
url: http://www.crypti.cc

myfullname: Adam Pritchard

exclude:
- README.md
- node_modules
- less

titleprefix: adam-p

navigation:
- text: Blog
  url: /blog/
  name: blog
- text: Projects
  url: /projects/
  name: projects
- text: CV
  url: /cv/
  name: cv
- text: Contact
  url: /contact/
  name: contact

permalink: /blog/:year/:month/:day/:title
