baseURL: 'https://adam-p.ca/'
languageCode: 'en-us'
title: 'adam-p'

languages:
  en:
    languageName: English
    menu:
      main:
        - url: /blog/
          name: Blog
          weight: 1
        - url: /inco/
          name: In/Co
          weight: 2
        - url: /projects/
          name: Projects
          weight: 3
        - url: /cv/
          name: CV
          weight: 4

permalinks:
  blog: 'blog/:year/:month/:slug/'
  inco: 'inco/:year/:month/:slug/'
  unpub: 'unpub/:year/:month/:slug/'

markup:
  goldmark:
    renderer:
      unsafe: True
  highlight:
    style: monokailight
  tableOfContents:
    startLevel: 2
    endLevel: 5
    ordered: false

relativeURLs: True

# Override the RSS feed filename from index.xml to feed.xml to match the name used by the old Jekyll site
outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

# Allows last git change date for .Page.Lastmod
enableGitInfo: True
